[package]
name = "rusty_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.18", features = ["json"] }
futures = "0.3.28"
serde_json = "1.0.104"
async-recursion = "1.0.4"
dioxus = "0.4.0"
dioxus-web = "0.4.0"
serde = { version = "1.0.180", features = ["derive"] }
sled = "0.34.7"
bincode = "2.0.0-rc.3"
feed-rs = "1.3.0"
tokio = { version = "1.29.1", features = ["full"] }