[package]
name = "rusty_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.18"
tokio = { version = "1.29.1", features = ["full"] }
feed-rs = "1.3.0"
chrono = "0.4.26"
sled = "0.34.7"
bincode = "2.0.0-rc.3"
