[package]
name = "rusty_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
dioxus = "0.4.0"
dioxus-web = "0.4.0"
# sled = "0.34.7"
atom_syndication = { version = "0.12.2", features = ["with-serde"] }
