[package]
name = "rusty_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.177"
toml = "0.7.6"
serde_derive = "1.0.177"
reqwest = "0.11.18"
tokio = { version = "1.29.1", features = ["full"] }
feed-rs = "1.3.0"
