[package]
name = "rusty_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
reqwest = { version = "0.11.18", features = ["json"] }
futures = "0.3.28"
serde_json = "1.0.104"
async-recursion = "1.0.4"
dioxus = "0.4.0"
dioxus-web = "0.4.0"
serde = { version = "1.0.180", features = ["derive"] }
