[application]
name = "Rusty Reader"
default_platform = "web"
out_dir = "dist"

[web.app]
title = "Rusty Reader"

[web.watcher]
watch_path = ["src"]

[web.resource]
style = ["style.css"]
script = []

[web.resource.dev]
script = []
