version: "3"

services:
    rusty_reader:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - STABLE_DIFFUSION_API_KEY=${STABLE_DIFFUSION_API_KEY}
        restart: always
