[[rss]]
category = "informative"
rss_url = "https://www.theverge.com/rss/index.xml"
title = "The Verge"
icon = "https://www.theverge.com/favicon.ico"
dominant_color = "#5200ff"

[[rss]]
category = "informative"
rss_url = "https://www.tomshardware.com/rss.xml"
title = "Tom's Hardware: For The Hardcore PC Enthusiast"
icon = "https://www.tomshardware.com/favicon.ico"
dominant_color = "#d82329"

[[rss]]
category = "informative"
rss_url = "http://feeds.bbci.co.uk/news/technology/rss.xml"
title = "BBC - Home"
icon = "https://www.bbc.co.uk/favicon.ico"
dominant_color = "#dc143c"

[[rss]]
category = "informative"
rss_url = "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml"
title = "BBC - Home"
icon = "https://www.bbc.co.uk/favicon.ico"
dominant_color = "#dc143c"

[[rss]]
category = "asoiaf"
rss_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCQzdMyuz0Lf4zo4uGcEujFw"
title = "GameofThrones"
icon = "http://www.youtube.com/favicon.ico"
dominant_color = "#ff0000"

[[rss]]
category = "entertainment"
rss_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw"
title = "Linus Tech Tips"
icon = "http://www.youtube.com/favicon.ico"
dominant_color = "#ff0000"
