[[rss]]
category = "informative"
rss_url = "https://www.theverge.com/rss/index.xml"
title = "The Verge"
icon = "https://www.theverge.com/favicon.ico"
dominant_color = "#5200ff"

[[rss]]
category = "informative"
rss_url = "http://feeds.bbci.co.uk/news/technology/rss.xml"
title = "BBC - Home"
icon = "https://www.bbc.co.uk/favicon.ico"
dominant_color = "#dc143c"

[[rss]]
category = "informative"
rss_url = "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml"
title = "BBC - Home"
icon = "https://www.bbc.co.uk/favicon.ico"
dominant_color = "#dc143c"

[[rss]]
category = "asoiaf"
rss_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCQzdMyuz0Lf4zo4uGcEujFw"
title = "GameofThrones"
icon = "https://pipedproxy.kavin.rocks/ytc/AOPolaQHL4C2izzkfiuRwuv43mPsky8mCpk_Jmq9oKvznw=s48-c-k-c0x00ffffff-no-rw?host=yt3.googleusercontent.com"
dominant_color = "#181721"

[[rss]]
category = "entertainment"
rss_url = "https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw"
title = "Linus Tech Tips"
icon = "https://pipedproxy.kavin.rocks/Vy6KL7EM_apxPSxF0pPy5w_c87YDTOlBQo3MADDF0Wl51kwxmt9wmRotnt2xQXwlrcyO0Xe56w=s48-c-k-c0x00ffffff-no-rw?host=yt3.googleusercontent.com"
dominant_color = "#fe4d00"
