[[rss]]
rss_url = "https://www.theverge.com/rss/index.xml"
link = "https://www.theverge.com"
title = "The Verge"
icon = "https://www.theverge.com/favicon.ico"
dominant_color = "#5200ff"

[[rss]]
rss_url = "https://www.tomshardware.com/rss.xml"
link = "https://www.tomshardware.com"
title = "Tom's Hardware: For The Hardcore PC Enthusiast"
icon = "https://www.tomshardware.com/favicon.ico"
dominant_color = "#d82329"

[[rss]]
rss_url = "https://hnrss.org/frontpage"
link = "https://news.ycombinator.com"
title = "Hacker News"
icon = "https://news.ycombinator.com/favicon.ico"
dominant_color = "#ff6600"

[[rss]]
rss_url = "http://feeds.bbci.co.uk/news/technology/rss.xml"
link = "https://www.bbc.co.uk"
title = "BBC - Home"
icon = "https://www.bbc.co.uk/favicon.ico"
dominant_color = "#dc143c"

[[rss]]
rss_url = "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml"
link = "https://www.bbc.co.uk"
title = "BBC - Home"
icon = "https://www.bbc.co.uk/favicon.ico"
dominant_color = "#dc143c"
